### ISSUE TITLE
Files cannot be saved to a newly created encfs volume

### ISSUE THREAD

**Issue by Zero3** [jetwhiz/encfs4win#53] opened 2016-08-02 08:57 UTC
# Environment
 * Windows version: Windows 7
 * Processor architecture: 64-bit
 * Encfs4win version: 1.10.1-RC8
 * Dokan version (legacy, modern): modern

## Steps to reproduce problem

1) `encfs D:\Enc D:\Dec`

2) Use standard configuration and any password

3) Open notepad

4) Try to save the empty file to the mounted folder (`D:\Dec` in my case)

5) Observe failure to save file:

![image](https://cloud.githubusercontent.com/assets/82504/17322706/11949df0-589f-11e6-9bf7-b05f6e5821d4.png)

**Comment by jetwhiz** [comment] 2016-08-03 00:52
@Zero3 -- is this a clean installation of encfs and Dokany?  I've tested this out on various platforms and do not seem to experience this issue.  I would recommend completely uninstalling both Dokany and encfs, restarting, and installing encfs RC8 fresh.

**Comment by Zero3** [comment] 2016-08-03 09:01
@jetwhiz Yup, clean install. I will try reinstalling and testing again.

I did create (with encfs) and delete (with explorer) the `enc` and `dec` folders several times because of https://github.com/jetwhiz/encfs4win/issues/52 though, so maybe this was caused by some stale state in encfs/Dokany/Windows or something like that?

**Comment by jetwhiz** [comment] 2016-08-03 14:00
@Zero3 -- that could be what's causing it -- can you try this again after testing the patch for issue #52?

**Comment by gzl6** [comment] 2016-08-18 13:29
I just follow @Zero3's steps. same issue on me.

**Comment by jetwhiz** [comment] 2016-08-18 13:45
@gzl6 -- You experience these issues when you mount to a drive letter?  e.g., 

````cmd
encfs   D:\Enc   Z:
````

Also, this is with the latest version of encfs4win ([1.10.1-RC8](https://github.com/jetwhiz/encfs4win/releases/tag/1.10.1-RC8))?

**Comment by gzl6** [comment] 2016-08-19 02:53
>@gzl6 -- You experience these issues when you mount to a drive letter? e.g.,
Mount to a driver root has no issues.
I just follow @Zero3 steps to mount on folder found the problem.
And it is strange why mount to a folder need to create it first. It should be virtual folder.
![ashampoo_snap_2016 08 19_10h47m09s_001_ - encfs d--test d--dec](https://cloud.githubusercontent.com/assets/20939122/17797333/a418b69e-65fa-11e6-819b-752bb2303c13.jpg)


>Also, this is with the latest version of encfs4win (1.10.1-RC8)?
Here is sytem info:
    Windows version: windows 10 64bit
    Processor architecture:
    Encfs4win version: 1.10.1-RC8
    Dokan version (legacy, modern): modern

**Comment by jetwhiz** [comment] 2016-08-20 14:28
@gzl6 -- that part is a known issue with Dokan ([1.10.1-RC8](https://github.com/jetwhiz/encfs4win/releases/tag/1.10.1-RC8)).  

Even the old version of encfs4win (http://members.ferrara.linux.it/freddy77/encfs.html) stated "NOTE: Windows 7 users should use a drive (like "X:") as plain_dir to avoid case sensitive problems which results in file/folder not found problems.".  

At least for now, you must mount to a drive letter when using encfs on Windows.

**Comment by jetwhiz** [comment] 2016-08-20 14:29
I'm going to mark this as a duplicate of issue #51

**Closed** 2016-08-20 14:30 UTC
Labels: duplicate
