### ISSUE TITLE
Can't move a folder from mounted drive to a regular drive

### ISSUE THREAD

**Issue by ultimate-deej** [jetwhiz/encfs4win#24] opened 2016-04-30 23:19 UTC
I have a 250 MB folder with ~1000 files and ~400 folders.
I was able to successfully move it to encfs mounted drive. Everything looks good, the sizes match, as well as the number of files/dirs.

Now when I try to move it back, everything remain on the encfs volume, and the file move dialog closes without errors. At the destination location a folder is created with some inner folder in it, but there is no files.

Also, when I try to open individual files, some are opening and some are not, depending on the app used. For example, Notepad can open files and Microsoft Reader can't.

I use Windows 10, SSD drive, encfs4win v1.10.1-RC1.

**Comment by jetwhiz** [comment] 2016-05-01 01:04
Hi @ultimate-deej -- do you know if this issue exists for you also in release [v1.9.0-RC4](https://github.com/jetwhiz/encfs4win/releases/tag/v1.9.0-RC4)?

**Comment by ultimate-deej** [comment] 2016-05-17 21:14
It appears to exist in 1.9.0-RC4, 1.10.1-RC1 and v1.10.1-RC4.
I also noticed that copying the folder always completes without any problems.

**Comment by jetwhiz** [comment] 2016-05-19 21:23
I think this issue is related to Windows locking files in a folder, which will make the folder impossible to fully move (or rename).  Have you tried restarting encfs and then moving the folder (to ensure no files are locked)?

**Comment by ultimate-deej** [comment] 2016-05-22 14:51
Didn't help

**Comment by jetwhiz** [comment] 2016-05-22 17:41
Have you tried running with verbose "-v" turned on to see if there are any errors printed out on the command line?  And are there any patterns you notice of which files are moved and which are not?  

In order to debug and find the problem, we need to figure out a way to make this reproducible.

**Comment by gh223682** [comment] 2016-05-22 22:48
@ultimate-deej @jetwhiz I had something similar happen when I tried to delete some folders on the virtual drive in explorer. The deletion completed without any errors, and the folder seemed to have disappeared as expected. But when I refreshed the folder view, the deleted folder and all of its contents were still there.

In my case, I had to delete the folder manually from the physical drive to get it to disappear from the virtual drive. I didn't run into any permissions or locking issues deleting from the physical drive, so I don't believe it was a filesystem issue per se.

However, I think there is some incompatibility introduced with FUSE where permissions and errors are not being handled correctly.

For example, I am migrating an BoxCryptor Classic (which uses EncFS) to EncFS4Win. I previously didn't have any problems deleting folders created using BoxCryptor while using BoxCryptor. But I am having problems deleting those same folders using EncFS4Win.

I would do more to debug, but encfs.exe in verbose "-v" mode causes system instability for me. See: Issue #32.

**Comment by jetwhiz** [comment] 2016-05-23 23:27
@gh223682  -- does this only happen when there are a lot of files in your encrypted folder, or even with a small sample set?  I don't appear to experience this on my end (though I only have small folders typically).

**Comment by gh223682** [comment] 2016-05-24 01:39
@jetwhiz Okay, I've done some more troubleshooting and I have more to report.

I've determined that--at the very least--the presence of a desktop.ini file is causing problems for the parent folders which cannot be deleted from the virtual drive.

Changing this desktop.ini file to a non-hidden and non-system file:

`% attrib -h -s desktop.ini`

and deleting the desktop.ini file enabled me to delete the parent folder.

I'm not sure if this is an EncFS4Win problem or a Dokan problem.

I'm also investigating potential problems caused by mis-ordered permissions in the physical drive, since I did an in-place upgrade of Windows 7 to Windows 10 and there are some screwy permissions issues which seem like they might also be causing problems. But it's hard for me to find test examples since fixing the permissions on these files was one of the first things that I did after upgrading.

I'll report back here if I find anything.

**Comment by gh223682** [comment] 2016-05-24 01:47
> does this only happen when there are a lot of files in your encrypted folder, or even with a small sample set? I don't appear to experience this on my end (though I only have small folders typically).

@jetwhiz No, I don't have a lot of files in my folders either.

**Comment by gh223682** [comment] 2016-05-24 02:45
@jetwhiz An update to my earlier comment regarding desktop.ini files: it appears the presence of ANY files or folders prevents the deletion of a parent folder.

**Comment by jetwhiz** [comment] 2016-05-28 00:08
@gh223682 - From what I understand, this is the expected behavior when it comes to deleting a non-empty folder.  Windows Explorer should trigger a "rmdir" in FUSE when a folder is removed, and the FUSE specifications state that the folder must be empty in order to be deleted.  

To delete a non-empty folder, you must run "rd /S folder" to recursively delete everything in it, along with the folder.  Otherwise you will see an error in the logs stating that the folder isn't empty.

**Comment by gh223682** [comment] 2016-05-28 11:50
@jetwhiz The whole point of EncFS *4Win* is to provide a virtual filesystem which functions in no way differently than a separate physical filesystem.

EncFS should be transparent to: 1) the user; 2) any applications; and 3) the operating system for all native filesystem calls for creating, reading, writing, deleting, locking, etc. files.

Even though EncFS is doing exactly what it should do with respect to the actual filesystem calls, that doesn't make it usable in a way that users, applications, and the operating system are expecting. In addition to not being able to easily move and delete directories in explorer, programs like Adobe Photoshop are having a problem saving files to EncFS4Win directories because of differences in the allocation of temporary/lock files, returning an error, "The specified folder is not writable," when it is.

I think that the appropriate substitutions should be made to handle the cases where there are important differences, notably moving, deleting directories, and locking files.

**Comment by jetwhiz** [comment] 2016-05-28 14:41
@gh223682 My main concern is that moving a folder to the recycling bin is not an option with encfs4win, and so accidentally requesting the deletion of a folder could be disastrous for someone if we automatically recursive-delete everything.  

Maybe if we hook a MessageBox confirmation dialog into the process we can alert the user that something major and irreversible is about to happen if they continue.

**Comment by gh223682** [comment] 2016-05-29 01:23
> My main concern is that moving a folder to the recycling bin is not an option with encfs4win, and so accidentally requesting the deletion of a folder could be disastrous for someone if we automatically recursive-delete everything.

@jetwhiz I don't think that is really a big deal, at least it shouldn't be. For example, in Windows, network shares don't support a recycle bin, so users can already accidentally recursively delete everything. There are also other filesystems which don't support a recycle bin.

> Maybe if we hook a MessageBox confirmation dialog into the process we can alert the user that something major and irreversible is about to happen if they continue.

There is already a MessageBox confirmation in explorer alerting the user that the deletion is permanent:

> Are you sure you want to permanently delete this file?

> Are you sure you want to permanently delete this folder?

**Comment by dumblob** [comment] 2016-06-08 10:03
I must agree on this with @gh223682 . I'm convinced it's totally fine to let Explorer ask once and just believe in the user's answer. The full transparency and compatibility should really be way more important than a possible user mistake.

For example right now encfs4win is a no-go for me and my family members and colleagues at work, just because of this.

**Comment by jetwhiz** [comment] 2016-06-08 13:08
@gh223682 @ultimate-deej  Can you try this patch and see if it fixes the issue of moving/renaming folders?  

[patch.txt](https://github.com/jetwhiz/encfs4win/files/304811/patch.txt)


@dumblob @gh223682 I'm looking into IFileOperation to see if I can get Windows to do a recursive delete for us.  Hopefully I'll have a patch soon that we can put in RC7 that will fix this.

**Comment by jetwhiz** [comment] 2016-06-09 17:06
@dumblob @gh223682 Can you try this patch for the recursive delete of a folder functionality?  It seems to work well on my Windows 7 machine. 

[patch.txt](https://github.com/jetwhiz/encfs4win/files/307499/patch.txt)

**Comment by dumblob** [comment] 2016-06-09 18:06
@jetwhiz unfortunately I don't have the compilation environment set up right now.

I have though one additional question - what do you think about the rest of of @gh223682's proposal "I think that the appropriate substitutions should be made to handle the cases where there are important differences, notably moving, deleting directories, and locking files."?

I.e. *moving files and directories* (including moving outside of the encrypted folder to any unencrypted place) and *locking files* (e.g. Excel depends on them and without them one can't use Excel at all).

**Comment by jetwhiz** [comment] 2016-06-09 21:04
@dumblob We will try to keep the behavior consistent with Windows wherever possible.  AFAIK, moving and deleting files/folders should be working correctly with the above two patches.  

Regarding locking files, I'll look into getting this implemented.  The Dokany FUSE documentation says that it is not necessary to implement the lock() function since the library will automatically handle it for local files, but if Excel is not working then this might not be the case.

**Comment by gh223682** [comment] 2016-06-09 22:41
> Does Excel give an error saying it cannot lock the file? 

@jetwhiz Saving an Excel file to a volume mounted with 1.10.1-RC6 legacy causes encfs.exe to crash.

> 2016-06-09 18:23:16,287 VER [encfs.cpp:214] readdir on C:\EncFS/
> 2016-06-09 18:23:16,289 VER [encfs.cpp:214] readdir on open call, requestWrite = C:\EncFS/
> 2016-06-09 18:23:16,289 VER [RawFileIO.cpp:89] readdir on open call, requestWrite = C:\EncFS/0
> 2016-06-09 18:23:16,289 VER [RawFileIO.cpp:95] using existing file descriptor
> 2016-06-09 18:23:16,289 VER [encfs.cpp:576] encfs_open for C:\EncFS/~$Book1.xlsx, flags 0
> 2016-06-09 18:23:16,289 VER [RawFileIO.cpp:89] open call, requestWrite = 0
> 2016-06-09 18:23:16,289 VER [RawFileIO.cpp:95] using existing file descriptor
> 2016-06-09 18:23:16,290 VER [encfs.cpp:214] readdir on C:\EncFS/

Sometimes I get a FAT_FILE_SYSETM (fastfat.SYS) BSOD when I try to remount with encfs.exe.

I'll test in modern and report back.

**Comment by jetwhiz** [comment] 2016-06-10 00:17
@gh223682 @dumblob @ultimate-deej  The above patches are rolled up in -RC7 now.  Can you try the latest version to see if these issues have been fixed?  

> Saving an Excel file to a volume mounted with 1.10.1-RC6 legacy causes encfs.exe to crash.
This might be related to the fact that encfs_create was undefined in legacy.  I have added this callback for legacy.  Can you try again to see if this issue still exists?

**Comment by gh223682** [comment] 2016-06-10 02:28
> This might be related to the fact that encfs_create was undefined in legacy. I have added this callback for legacy. Can you try again with RC7 to see if this issue still exists? 

@jetwhiz Now with legacy 1.10.1-RC7, simply creating a file from the command line or via explorer causes encfs.exe to crash:

> CreateFile : \New Text Document.txt
> 	AccessMode: FILE_GENERIC_WRITE|FILE_GENERIC_READ|WRITE_DAC
> 	ShareMode: 0x0
> 	Disposition: CREATE_NEW (1)
> 	Flags: 128 (0x80)
> 2016-06-09 21:55:41,603 DEBUG [default] [int __thiscall encfs::RawFileIO::getAttr(struct _stat64 *) const] [RawFileIO.cpp:137] getAttr error on C:\EncFS/New Text Document.txt: No such file or directory
> 2016-06-09 21:55:41,603 DEBUG [default] [int __cdecl encfs::withFileNode(const char *,const char *,struct fuse_file_info *,class std::function<int __cdecl(class encfs::FileNode *)>)] [encfs.cpp:146] op: getattr error: No such file or directory
> 2016-06-09 21:55:41,603 VER [encfs.cpp:292] mknod on C:\EncFS/New Text Document.txt, mode 511, dev 0
> 2016-06-09 21:55:41,603 VER [RawFileIO.cpp:89] open call, requestWrite = 1
> 2016-06-09 21:55:41,603 VER [RawFileIO.cpp:110] open file with flags 2, result = 4
> 2016-06-09 21:55:41,603 VER [encfs.cpp:610] encfs_open for C:\EncFS/New Text Document.txt, flags 1282

**Comment by gh223682** [comment] 2016-06-10 02:51
> Can you try this patch and see if it fixes the issue of moving/renaming folders?
> Can you try this patch for the recursive delete of a folder functionality? It seems to work well on my Windows 7 machine.

@jetwhiz @ultimate-deej @dumblob Both patches (1.10.1-RC7 modern) are working for me in Windows 10. However, when I recursively delete a folder containing one file in explorer, it takes a really long time to complete, more than 30 seconds.

**Comment by jetwhiz** [comment] 2016-06-10 15:10
@gh223682 Are you able to open Excel files with modern now in -RC7?  

And the folder and everything in it deletes successfully after the delay?  Even after refreshing?

**Comment by jetwhiz** [comment] 2016-06-10 15:15
@gh223682 Regarding the legacy issue, it looks like Dokan v0.7.4 does not support the create callback then.  I will revert this change in the next version to fix this issue.

**Comment by gh223682** [comment] 2016-06-10 19:15
> Are you able to open Excel files with modern now in -RC7?

@jetwhiz Yes, but saving Excel files now takes more than 30 seconds.

> And the folder and everything in it deletes successfully after the delay? Even after refreshing?

Yes, the recursive folder deletes were successful.

> Does the debug info show anything happening during this delay?

There is just so much information in the debug logs over a 30-second period that it's difficult to figure out what's going on even if I run in single-threaded "-s" mode because the operating system is accessing data in the volume. Is there any way you can add something like an operation ID to the debugging information or something like that to make it easier to isolate what is going on?

Also, I discovered a new potential bug trying to debug this issue when I tried to create a second empty volume where encfs.exe is crashing whenever I try to mount it after the first successful mount and unmount. I will look into this further and file a report when I have more information.

> 2016-06-10 14:56:42,283 VER [main.cpp:538] Closing stderr
> 2016-06-10 14:56:42,844 VER [MACFileIO.cpp:70] fs block size = 1024, macBytes = 8, randBytes = 0

**Comment by jetwhiz** [comment] 2016-06-11 14:37
@gh223682  Everything is happening instantaneously when I try to delete folders, even when there is only one file.  Are you running in verbose mode when this happens?

**Comment by gh223682** [comment] 2016-06-11 16:42
> Everything is happening instantaneously when I try to delete folders, even when there is only one file. Are you running in verbose mode when this happens?

@jetwhiz This is still happening win Windows 10 without encfs.exe verbose mode, and no debugging for Dokan.

If I use rmdir from the command line, recursive deletes are instaneous, though.

**Comment by gh223682** [comment] 2016-06-11 16:53
@jetwhiz I just noticed that the temporary files created during saving Excel files are not getting deleted properly. They are hidden with both the system and hidden attribute flags, which is why I didn't notice them earlier.

For example, if I am save Book1.xlsx, the temporary file ~Book1.xlsx is created, but it is never deleted. If I save Book1.xlsx on a regular NTFS volume, the temporary file is deleted after the save and exit.

**Comment by jetwhiz** [comment] 2016-06-11 17:38
@gh223682  I expect that Excel is using the FILE_FLAG_DELETE_ON_CLOSE attribute to pull this functionality off, which unfortunately is not supported by Dokany.  Doubly unfortunate is that this attribute cannot be set with SetFileAttributesW (it must be set on file creation).

**Comment by gh223682** [comment] 2016-06-11 17:52
>  I expect that Excel is using the FILE_FLAG_DELETE_ON_CLOSE attribute to pull this functionality off, which unfortunately is not supported by Dokany.

@jetwhiz It seems to me that these differences should be resolved by Dokany, and not by the individual projects like EncFS4Win.

Do you think that it would be too difficult to lobby to get this kind of fairly typical Windows functionality included in Dokany (even though it's at the pre-release stage), or do does that project take a more least-common denominator approach to maximize compatibility?

**Comment by dumblob** [comment] 2016-06-12 12:15
@jetwhiz I'm sorry for being so late. I've tested `1.10.1-RC7` with my friend (who is kind of a professional on testing Windows applications and knows some Windows internals) on Win 7 with bundled Dokany and among other usability and functional issues like frequent crashes (which I'll report later as I'm out of time right now) recursive deletion worked without any issues.

@gh223682 regarding slow operations you experienced, it might be caused by virtualized paths which Windows start to automatically use to overcome the extremely limited length of a path (just [260 bytes](https://github.com/daokoder/dao-modules/issues/67 )). Did you try to mount encfs4win folder to some very shallow nested folder and using only very short file & folder names?

**Comment by jetwhiz** [comment] 2016-06-12 23:11
@gh223682  I've submitted a feature request with Dokany, so we'll see what happens. Without support from Dokany, there is no way for our program to know when DELETE_ON_CLOSE has been requested. 

@dumblob Thanks for the update!  I'm looking forward to seeing the details on the frequent crashes when you get a chance to submit this bug report.  

Since the core of this issue looks like it is now fixed, I'm going to close this issue for now.  If you notice any new or related issues then please submit them as a new issue.

**Closed by jetwhiz** 2016-06-12 23:11 UTC
Labels: bug, help wanted, waiting for feedback

**Comment by ultimate-deej** [comment] 2016-06-16 15:57
Sorry for not replying earlier.
I've just tested the latest 1.10.1-RC7 release, and things became even worse. Now it creates an empty folder at destination, and the source folder is simply deleted. Something's wrong with moving.

**Comment by jetwhiz** [comment] 2016-06-19 16:55
@ultimate-deej - I don't seem to be experiencing this issue with my Windows 10 64-bit and Windows 7 32-bit machines.  Can you give some more details about your installs and process?  Is this a clean install of Dokan and encfs4win?  Do you also experience this issue with a newly-created encfs filesystem (or only with your existing FS)?
